basePath: /api/v1
definitions:
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  model.Weather:
    properties:
      current:
        properties:
          cloud:
            type: integer
          condition:
            properties:
              code:
                type: integer
              icon:
                type: string
              text:
                type: string
            type: object
          feelslike_c:
            type: number
          feelslike_f:
            type: number
          gust_kph:
            type: number
          gust_mph:
            type: number
          humidity:
            type: integer
          is_day:
            type: integer
          last_updated:
            type: string
          last_updated_epoch:
            type: integer
          precip_in:
            type: number
          precip_mm:
            type: number
          pressure_in:
            type: number
          pressure_mb:
            type: number
          temp_c:
            type: number
          temp_f:
            type: number
          uv:
            type: number
          vis_km:
            type: number
          vis_miles:
            type: number
          wind_degree:
            type: integer
          wind_dir:
            type: string
          wind_kph:
            type: number
          wind_mph:
            type: number
        type: object
      location:
        properties:
          country:
            type: string
          lat:
            type: number
          localtime:
            type: string
          localtime_epoch:
            type: integer
          lon:
            type: number
          name:
            type: string
          region:
            type: string
          tz_id:
            type: string
        type: object
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /rain:
    get:
      consumes:
      - application/json
      description: get rain status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Get rain status
      tags:
      - rain
  /weather/{city}:
    get:
      consumes:
      - application/json
      description: get weather by city
      parameters:
      - description: City
        in: path
        name: city
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Weather'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Get weather by city
      tags:
      - weather
swagger: "2.0"
